//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSignageUI.TvsServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TvsInfoWTO", Namespace="http://schemas.datacontract.org/2004/07/DigitalServices.Model")]
    [System.SerializableAttribute()]
    public partial class TvsInfoWTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long alarm_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long category_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long companyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string companyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int content_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string identifyKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string identifyShortKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int isDirtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long lastAliveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int xField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int yField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long alarm_id {
            get {
                return this.alarm_idField;
            }
            set {
                if ((this.alarm_idField.Equals(value) != true)) {
                    this.alarm_idField = value;
                    this.RaisePropertyChanged("alarm_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long category_id {
            get {
                return this.category_idField;
            }
            set {
                if ((this.category_idField.Equals(value) != true)) {
                    this.category_idField = value;
                    this.RaisePropertyChanged("category_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long companyId {
            get {
                return this.companyIdField;
            }
            set {
                if ((this.companyIdField.Equals(value) != true)) {
                    this.companyIdField = value;
                    this.RaisePropertyChanged("companyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string companyName {
            get {
                return this.companyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.companyNameField, value) != true)) {
                    this.companyNameField = value;
                    this.RaisePropertyChanged("companyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int content_id {
            get {
                return this.content_idField;
            }
            set {
                if ((this.content_idField.Equals(value) != true)) {
                    this.content_idField = value;
                    this.RaisePropertyChanged("content_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string identifyKey {
            get {
                return this.identifyKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.identifyKeyField, value) != true)) {
                    this.identifyKeyField = value;
                    this.RaisePropertyChanged("identifyKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string identifyShortKey {
            get {
                return this.identifyShortKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.identifyShortKeyField, value) != true)) {
                    this.identifyShortKeyField = value;
                    this.RaisePropertyChanged("identifyShortKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ip {
            get {
                return this.ipField;
            }
            set {
                if ((object.ReferenceEquals(this.ipField, value) != true)) {
                    this.ipField = value;
                    this.RaisePropertyChanged("ip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int isDirty {
            get {
                return this.isDirtyField;
            }
            set {
                if ((this.isDirtyField.Equals(value) != true)) {
                    this.isDirtyField = value;
                    this.RaisePropertyChanged("isDirty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long lastAlive {
            get {
                return this.lastAliveField;
            }
            set {
                if ((this.lastAliveField.Equals(value) != true)) {
                    this.lastAliveField = value;
                    this.RaisePropertyChanged("lastAlive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int x {
            get {
                return this.xField;
            }
            set {
                if ((this.xField.Equals(value) != true)) {
                    this.xField = value;
                    this.RaisePropertyChanged("x");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int y {
            get {
                return this.yField;
            }
            set {
                if ((this.yField.Equals(value) != true)) {
                    this.yField = value;
                    this.RaisePropertyChanged("y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TvCategoreisInfoWTO", Namespace="http://schemas.datacontract.org/2004/07/DigitalServices.Model")]
    [System.SerializableAttribute()]
    public partial class TvCategoreisInfoWTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long companyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string companyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long parent_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long companyId {
            get {
                return this.companyIdField;
            }
            set {
                if ((this.companyIdField.Equals(value) != true)) {
                    this.companyIdField = value;
                    this.RaisePropertyChanged("companyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string companyName {
            get {
                return this.companyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.companyNameField, value) != true)) {
                    this.companyNameField = value;
                    this.RaisePropertyChanged("companyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long parent_id {
            get {
                return this.parent_idField;
            }
            set {
                if ((this.parent_idField.Equals(value) != true)) {
                    this.parent_idField = value;
                    this.RaisePropertyChanged("parent_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagingInfo", Namespace="http://schemas.datacontract.org/2004/07/DigitalServices.Model")]
    [System.SerializableAttribute()]
    public partial class PagingInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DigitalSignageUI.TvsServices.OrderInfo[] orderLstField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pageNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pageSizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DigitalSignageUI.TvsServices.OrderInfo[] orderLst {
            get {
                return this.orderLstField;
            }
            set {
                if ((object.ReferenceEquals(this.orderLstField, value) != true)) {
                    this.orderLstField = value;
                    this.RaisePropertyChanged("orderLst");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                if ((this.pageNumberField.Equals(value) != true)) {
                    this.pageNumberField = value;
                    this.RaisePropertyChanged("pageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                if ((this.pageSizeField.Equals(value) != true)) {
                    this.pageSizeField = value;
                    this.RaisePropertyChanged("pageSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderInfo", Namespace="http://schemas.datacontract.org/2004/07/DigitalServices.Model")]
    [System.SerializableAttribute()]
    public partial class OrderInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sortTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orderName {
            get {
                return this.orderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.orderNameField, value) != true)) {
                    this.orderNameField = value;
                    this.RaisePropertyChanged("orderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sortType {
            get {
                return this.sortTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.sortTypeField, value) != true)) {
                    this.sortTypeField = value;
                    this.RaisePropertyChanged("sortType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TvContentsInfoWTO", Namespace="http://schemas.datacontract.org/2004/07/DigitalServices.Model")]
    [System.SerializableAttribute()]
    public partial class TvContentsInfoWTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long companyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long content_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int durationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long endTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int isDirtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long lastAliveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long lastViewedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long startTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long tv_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int xField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int yField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long companyId {
            get {
                return this.companyIdField;
            }
            set {
                if ((this.companyIdField.Equals(value) != true)) {
                    this.companyIdField = value;
                    this.RaisePropertyChanged("companyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long content_id {
            get {
                return this.content_idField;
            }
            set {
                if ((this.content_idField.Equals(value) != true)) {
                    this.content_idField = value;
                    this.RaisePropertyChanged("content_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int duration {
            get {
                return this.durationField;
            }
            set {
                if ((this.durationField.Equals(value) != true)) {
                    this.durationField = value;
                    this.RaisePropertyChanged("duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long endTime {
            get {
                return this.endTimeField;
            }
            set {
                if ((this.endTimeField.Equals(value) != true)) {
                    this.endTimeField = value;
                    this.RaisePropertyChanged("endTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ip {
            get {
                return this.ipField;
            }
            set {
                if ((object.ReferenceEquals(this.ipField, value) != true)) {
                    this.ipField = value;
                    this.RaisePropertyChanged("ip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int isDirty {
            get {
                return this.isDirtyField;
            }
            set {
                if ((this.isDirtyField.Equals(value) != true)) {
                    this.isDirtyField = value;
                    this.RaisePropertyChanged("isDirty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long lastAlive {
            get {
                return this.lastAliveField;
            }
            set {
                if ((this.lastAliveField.Equals(value) != true)) {
                    this.lastAliveField = value;
                    this.RaisePropertyChanged("lastAlive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long lastViewed {
            get {
                return this.lastViewedField;
            }
            set {
                if ((this.lastViewedField.Equals(value) != true)) {
                    this.lastViewedField = value;
                    this.RaisePropertyChanged("lastViewed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long startTime {
            get {
                return this.startTimeField;
            }
            set {
                if ((this.startTimeField.Equals(value) != true)) {
                    this.startTimeField = value;
                    this.RaisePropertyChanged("startTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long tv_id {
            get {
                return this.tv_idField;
            }
            set {
                if ((this.tv_idField.Equals(value) != true)) {
                    this.tv_idField = value;
                    this.RaisePropertyChanged("tv_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int x {
            get {
                return this.xField;
            }
            set {
                if ((this.xField.Equals(value) != true)) {
                    this.xField = value;
                    this.RaisePropertyChanged("x");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int y {
            get {
                return this.yField;
            }
            set {
                if ((this.yField.Equals(value) != true)) {
                    this.yField = value;
                    this.RaisePropertyChanged("y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TvsServices.Itvs")]
    public interface Itvs {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/addTV", ReplyAction="http://tempuri.org/Itvs/addTVResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<string> addTV(DigitalSignageUI.TvsServices.TvsInfoWTO tvsInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/addTV", ReplyAction="http://tempuri.org/Itvs/addTVResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<string>> addTVAsync(DigitalSignageUI.TvsServices.TvsInfoWTO tvsInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/editTV", ReplyAction="http://tempuri.org/Itvs/editTVResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<string> editTV(DigitalSignageUI.TvsServices.TvsInfoWTO tvsInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/editTV", ReplyAction="http://tempuri.org/Itvs/editTVResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<string>> editTVAsync(DigitalSignageUI.TvsServices.TvsInfoWTO tvsInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/addCategory", ReplyAction="http://tempuri.org/Itvs/addCategoryResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<string> addCategory(DigitalSignageUI.TvsServices.TvCategoreisInfoWTO tvCategoreisInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/addCategory", ReplyAction="http://tempuri.org/Itvs/addCategoryResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<string>> addCategoryAsync(DigitalSignageUI.TvsServices.TvCategoreisInfoWTO tvCategoreisInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/deleteTVS", ReplyAction="http://tempuri.org/Itvs/deleteTVSResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<string> deleteTVS(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/deleteTVS", ReplyAction="http://tempuri.org/Itvs/deleteTVSResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<string>> deleteTVSAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/deleteCategory", ReplyAction="http://tempuri.org/Itvs/deleteCategoryResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<string> deleteCategory(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/deleteCategory", ReplyAction="http://tempuri.org/Itvs/deleteCategoryResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<string>> deleteCategoryAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/isDirty", ReplyAction="http://tempuri.org/Itvs/isDirtyResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.TvsServices.TvsInfoWTO> isDirty(long tv_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/isDirty", ReplyAction="http://tempuri.org/Itvs/isDirtyResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.TvsServices.TvsInfoWTO>> isDirtyAsync(long tv_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/recordSecondPlayed", ReplyAction="http://tempuri.org/Itvs/recordSecondPlayedResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<bool> recordSecondPlayed(long content_ad_id, long tv_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/recordSecondPlayed", ReplyAction="http://tempuri.org/Itvs/recordSecondPlayedResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<bool>> recordSecondPlayedAsync(long content_ad_id, long tv_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/searchDataOnTvCategories", ReplyAction="http://tempuri.org/Itvs/searchDataOnTvCategoriesResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.TvsServices.TvCategoreisInfoWTO[]> searchDataOnTvCategories(DigitalSignageUI.TvsServices.TvCategoreisInfoWTO filter, DigitalSignageUI.TvsServices.PagingInfo paging);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/searchDataOnTvCategories", ReplyAction="http://tempuri.org/Itvs/searchDataOnTvCategoriesResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.TvsServices.TvCategoreisInfoWTO[]>> searchDataOnTvCategoriesAsync(DigitalSignageUI.TvsServices.TvCategoreisInfoWTO filter, DigitalSignageUI.TvsServices.PagingInfo paging);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/searchDataOnTvs", ReplyAction="http://tempuri.org/Itvs/searchDataOnTvsResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.TvsServices.TvsInfoWTO[]> searchDataOnTvs(DigitalSignageUI.TvsServices.TvsInfoWTO filter, DigitalSignageUI.TvsServices.PagingInfo paging);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/searchDataOnTvs", ReplyAction="http://tempuri.org/Itvs/searchDataOnTvsResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.TvsServices.TvsInfoWTO[]>> searchDataOnTvsAsync(DigitalSignageUI.TvsServices.TvsInfoWTO filter, DigitalSignageUI.TvsServices.PagingInfo paging);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/getTvContentWithIp", ReplyAction="http://tempuri.org/Itvs/getTvContentWithIpResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<string> getTvContentWithIp(string ip, long companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/getTvContentWithIp", ReplyAction="http://tempuri.org/Itvs/getTvContentWithIpResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<string>> getTvContentWithIpAsync(string ip, long companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/getTvInfo", ReplyAction="http://tempuri.org/Itvs/getTvInfoResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.TvsServices.TvContentsInfoWTO[]> getTvInfo(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/getTvInfo", ReplyAction="http://tempuri.org/Itvs/getTvInfoResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.TvsServices.TvContentsInfoWTO[]>> getTvInfoAsync(string key);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ItvsChannel : DigitalSignageUI.TvsServices.Itvs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ItvsClient : System.ServiceModel.ClientBase<DigitalSignageUI.TvsServices.Itvs>, DigitalSignageUI.TvsServices.Itvs {
        
        public ItvsClient() {
        }
        
        public ItvsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ItvsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItvsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItvsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<string> addTV(DigitalSignageUI.TvsServices.TvsInfoWTO tvsInfo) {
            return base.Channel.addTV(tvsInfo);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<string>> addTVAsync(DigitalSignageUI.TvsServices.TvsInfoWTO tvsInfo) {
            return base.Channel.addTVAsync(tvsInfo);
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<string> editTV(DigitalSignageUI.TvsServices.TvsInfoWTO tvsInfo) {
            return base.Channel.editTV(tvsInfo);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<string>> editTVAsync(DigitalSignageUI.TvsServices.TvsInfoWTO tvsInfo) {
            return base.Channel.editTVAsync(tvsInfo);
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<string> addCategory(DigitalSignageUI.TvsServices.TvCategoreisInfoWTO tvCategoreisInfo) {
            return base.Channel.addCategory(tvCategoreisInfo);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<string>> addCategoryAsync(DigitalSignageUI.TvsServices.TvCategoreisInfoWTO tvCategoreisInfo) {
            return base.Channel.addCategoryAsync(tvCategoreisInfo);
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<string> deleteTVS(long id) {
            return base.Channel.deleteTVS(id);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<string>> deleteTVSAsync(long id) {
            return base.Channel.deleteTVSAsync(id);
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<string> deleteCategory(long id) {
            return base.Channel.deleteCategory(id);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<string>> deleteCategoryAsync(long id) {
            return base.Channel.deleteCategoryAsync(id);
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.TvsServices.TvsInfoWTO> isDirty(long tv_id) {
            return base.Channel.isDirty(tv_id);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.TvsServices.TvsInfoWTO>> isDirtyAsync(long tv_id) {
            return base.Channel.isDirtyAsync(tv_id);
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<bool> recordSecondPlayed(long content_ad_id, long tv_id) {
            return base.Channel.recordSecondPlayed(content_ad_id, tv_id);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<bool>> recordSecondPlayedAsync(long content_ad_id, long tv_id) {
            return base.Channel.recordSecondPlayedAsync(content_ad_id, tv_id);
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.TvsServices.TvCategoreisInfoWTO[]> searchDataOnTvCategories(DigitalSignageUI.TvsServices.TvCategoreisInfoWTO filter, DigitalSignageUI.TvsServices.PagingInfo paging) {
            return base.Channel.searchDataOnTvCategories(filter, paging);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.TvsServices.TvCategoreisInfoWTO[]>> searchDataOnTvCategoriesAsync(DigitalSignageUI.TvsServices.TvCategoreisInfoWTO filter, DigitalSignageUI.TvsServices.PagingInfo paging) {
            return base.Channel.searchDataOnTvCategoriesAsync(filter, paging);
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.TvsServices.TvsInfoWTO[]> searchDataOnTvs(DigitalSignageUI.TvsServices.TvsInfoWTO filter, DigitalSignageUI.TvsServices.PagingInfo paging) {
            return base.Channel.searchDataOnTvs(filter, paging);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.TvsServices.TvsInfoWTO[]>> searchDataOnTvsAsync(DigitalSignageUI.TvsServices.TvsInfoWTO filter, DigitalSignageUI.TvsServices.PagingInfo paging) {
            return base.Channel.searchDataOnTvsAsync(filter, paging);
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<string> getTvContentWithIp(string ip, long companyId) {
            return base.Channel.getTvContentWithIp(ip, companyId);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<string>> getTvContentWithIpAsync(string ip, long companyId) {
            return base.Channel.getTvContentWithIpAsync(ip, companyId);
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.TvsServices.TvContentsInfoWTO[]> getTvInfo(string key) {
            return base.Channel.getTvInfo(key);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.TvsServices.TvContentsInfoWTO[]>> getTvInfoAsync(string key) {
            return base.Channel.getTvInfoAsync(key);
        }
    }
}
