//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSignageUI.LiveVideosServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LiveTVInfoWTO", Namespace="http://schemas.datacontract.org/2004/07/DigitalServices.Model")]
    [System.SerializableAttribute()]
    public partial class LiveTVInfoWTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string channelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long companyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string companyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long content_ad_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nameIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int positionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string urlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string channel {
            get {
                return this.channelField;
            }
            set {
                if ((object.ReferenceEquals(this.channelField, value) != true)) {
                    this.channelField = value;
                    this.RaisePropertyChanged("channel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long companyId {
            get {
                return this.companyIdField;
            }
            set {
                if ((this.companyIdField.Equals(value) != true)) {
                    this.companyIdField = value;
                    this.RaisePropertyChanged("companyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string companyName {
            get {
                return this.companyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.companyNameField, value) != true)) {
                    this.companyNameField = value;
                    this.RaisePropertyChanged("companyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long content_ad_id {
            get {
                return this.content_ad_idField;
            }
            set {
                if ((this.content_ad_idField.Equals(value) != true)) {
                    this.content_ad_idField = value;
                    this.RaisePropertyChanged("content_ad_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int interval {
            get {
                return this.intervalField;
            }
            set {
                if ((this.intervalField.Equals(value) != true)) {
                    this.intervalField = value;
                    this.RaisePropertyChanged("interval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nameId {
            get {
                return this.nameIdField;
            }
            set {
                if ((this.nameIdField.Equals(value) != true)) {
                    this.nameIdField = value;
                    this.RaisePropertyChanged("nameId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int position {
            get {
                return this.positionField;
            }
            set {
                if ((this.positionField.Equals(value) != true)) {
                    this.positionField = value;
                    this.RaisePropertyChanged("position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                if ((object.ReferenceEquals(this.urlField, value) != true)) {
                    this.urlField = value;
                    this.RaisePropertyChanged("url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LiveVideosServices.IliveVideos")]
    public interface IliveVideos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IliveVideos/addLiveVideo", ReplyAction="http://tempuri.org/IliveVideos/addLiveVideoResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<string> addLiveVideo(DigitalSignageUI.LiveVideosServices.LiveTVInfoWTO videos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IliveVideos/addLiveVideo", ReplyAction="http://tempuri.org/IliveVideos/addLiveVideoResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<string>> addLiveVideoAsync(DigitalSignageUI.LiveVideosServices.LiveTVInfoWTO videos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IliveVideos/loadLiveContentsAds", ReplyAction="http://tempuri.org/IliveVideos/loadLiveContentsAdsResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.LiveVideosServices.LiveTVInfoWTO[]> loadLiveContentsAds(long content_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IliveVideos/loadLiveContentsAds", ReplyAction="http://tempuri.org/IliveVideos/loadLiveContentsAdsResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.LiveVideosServices.LiveTVInfoWTO[]>> loadLiveContentsAdsAsync(long content_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IliveVideos/loadLivesTvAds", ReplyAction="http://tempuri.org/IliveVideos/loadLivesTvAdsResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.LiveVideosServices.LiveTVInfoWTO[]> loadLivesTvAds(long content_id, long companyId, int position);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IliveVideos/loadLivesTvAds", ReplyAction="http://tempuri.org/IliveVideos/loadLivesTvAdsResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.LiveVideosServices.LiveTVInfoWTO[]>> loadLivesTvAdsAsync(long content_id, long companyId, int position);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IliveVideos/searchContentsWithLiveItem", ReplyAction="http://tempuri.org/IliveVideos/searchContentsWithLiveItemResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.LiveVideosServices.LiveTVInfoWTO[]> searchContentsWithLiveItem(long content_id, int position);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IliveVideos/searchContentsWithLiveItem", ReplyAction="http://tempuri.org/IliveVideos/searchContentsWithLiveItemResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.LiveVideosServices.LiveTVInfoWTO[]>> searchContentsWithLiveItemAsync(long content_id, int position);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IliveVideosChannel : DigitalSignageUI.LiveVideosServices.IliveVideos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IliveVideosClient : System.ServiceModel.ClientBase<DigitalSignageUI.LiveVideosServices.IliveVideos>, DigitalSignageUI.LiveVideosServices.IliveVideos {
        
        public IliveVideosClient() {
        }
        
        public IliveVideosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IliveVideosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IliveVideosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IliveVideosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<string> addLiveVideo(DigitalSignageUI.LiveVideosServices.LiveTVInfoWTO videos) {
            return base.Channel.addLiveVideo(videos);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<string>> addLiveVideoAsync(DigitalSignageUI.LiveVideosServices.LiveTVInfoWTO videos) {
            return base.Channel.addLiveVideoAsync(videos);
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.LiveVideosServices.LiveTVInfoWTO[]> loadLiveContentsAds(long content_id) {
            return base.Channel.loadLiveContentsAds(content_id);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.LiveVideosServices.LiveTVInfoWTO[]>> loadLiveContentsAdsAsync(long content_id) {
            return base.Channel.loadLiveContentsAdsAsync(content_id);
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.LiveVideosServices.LiveTVInfoWTO[]> loadLivesTvAds(long content_id, long companyId, int position) {
            return base.Channel.loadLivesTvAds(content_id, companyId, position);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.LiveVideosServices.LiveTVInfoWTO[]>> loadLivesTvAdsAsync(long content_id, long companyId, int position) {
            return base.Channel.loadLivesTvAdsAsync(content_id, companyId, position);
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.LiveVideosServices.LiveTVInfoWTO[]> searchContentsWithLiveItem(long content_id, int position) {
            return base.Channel.searchContentsWithLiveItem(content_id, position);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.LiveVideosServices.LiveTVInfoWTO[]>> searchContentsWithLiveItemAsync(long content_id, int position) {
            return base.Channel.searchContentsWithLiveItemAsync(content_id, position);
        }
    }
}
