//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSignageUI.AlarmsServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlarmsInfoWTO", Namespace="http://schemas.datacontract.org/2004/07/DigitalServices.Model")]
    [System.SerializableAttribute()]
    public partial class AlarmsInfoWTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long companyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string companyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long companyId {
            get {
                return this.companyIdField;
            }
            set {
                if ((this.companyIdField.Equals(value) != true)) {
                    this.companyIdField = value;
                    this.RaisePropertyChanged("companyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string companyName {
            get {
                return this.companyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.companyNameField, value) != true)) {
                    this.companyNameField = value;
                    this.RaisePropertyChanged("companyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagingInfo", Namespace="http://schemas.datacontract.org/2004/07/DigitalServices.Model")]
    [System.SerializableAttribute()]
    public partial class PagingInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DigitalSignageUI.AlarmsServices.OrderInfo[] orderLstField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pageNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pageSizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DigitalSignageUI.AlarmsServices.OrderInfo[] orderLst {
            get {
                return this.orderLstField;
            }
            set {
                if ((object.ReferenceEquals(this.orderLstField, value) != true)) {
                    this.orderLstField = value;
                    this.RaisePropertyChanged("orderLst");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                if ((this.pageNumberField.Equals(value) != true)) {
                    this.pageNumberField = value;
                    this.RaisePropertyChanged("pageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                if ((this.pageSizeField.Equals(value) != true)) {
                    this.pageSizeField = value;
                    this.RaisePropertyChanged("pageSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderInfo", Namespace="http://schemas.datacontract.org/2004/07/DigitalServices.Model")]
    [System.SerializableAttribute()]
    public partial class OrderInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sortTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orderName {
            get {
                return this.orderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.orderNameField, value) != true)) {
                    this.orderNameField = value;
                    this.RaisePropertyChanged("orderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sortType {
            get {
                return this.sortTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.sortTypeField, value) != true)) {
                    this.sortTypeField = value;
                    this.RaisePropertyChanged("sortType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AlarmsServices.Ialarms")]
    public interface Ialarms {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ialarms/deleteAlarm", ReplyAction="http://tempuri.org/Ialarms/deleteAlarmResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<string> deleteAlarm(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ialarms/deleteAlarm", ReplyAction="http://tempuri.org/Ialarms/deleteAlarmResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<string>> deleteAlarmAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ialarms/saveAlarm", ReplyAction="http://tempuri.org/Ialarms/saveAlarmResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<string> saveAlarm(DigitalSignageUI.AlarmsServices.AlarmsInfoWTO alarms, string tv_ids, long companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ialarms/saveAlarm", ReplyAction="http://tempuri.org/Ialarms/saveAlarmResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<string>> saveAlarmAsync(DigitalSignageUI.AlarmsServices.AlarmsInfoWTO alarms, string tv_ids, long companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ialarms/searchDataOnAlarms", ReplyAction="http://tempuri.org/Ialarms/searchDataOnAlarmsResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.AlarmsServices.AlarmsInfoWTO[]> searchDataOnAlarms(DigitalSignageUI.AlarmsServices.AlarmsInfoWTO filter, DigitalSignageUI.AlarmsServices.PagingInfo paging);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ialarms/searchDataOnAlarms", ReplyAction="http://tempuri.org/Ialarms/searchDataOnAlarmsResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.AlarmsServices.AlarmsInfoWTO[]>> searchDataOnAlarmsAsync(DigitalSignageUI.AlarmsServices.AlarmsInfoWTO filter, DigitalSignageUI.AlarmsServices.PagingInfo paging);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ialarms/loadTvAlarms", ReplyAction="http://tempuri.org/Ialarms/loadTvAlarmsResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.AlarmsServices.AlarmsInfoWTO[]> loadTvAlarms(long tvId, long companyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ialarms/loadTvAlarms", ReplyAction="http://tempuri.org/Ialarms/loadTvAlarmsResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.AlarmsServices.AlarmsInfoWTO[]>> loadTvAlarmsAsync(long tvId, long companyId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IalarmsChannel : DigitalSignageUI.AlarmsServices.Ialarms, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IalarmsClient : System.ServiceModel.ClientBase<DigitalSignageUI.AlarmsServices.Ialarms>, DigitalSignageUI.AlarmsServices.Ialarms {
        
        public IalarmsClient() {
        }
        
        public IalarmsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IalarmsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IalarmsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IalarmsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<string> deleteAlarm(long id) {
            return base.Channel.deleteAlarm(id);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<string>> deleteAlarmAsync(long id) {
            return base.Channel.deleteAlarmAsync(id);
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<string> saveAlarm(DigitalSignageUI.AlarmsServices.AlarmsInfoWTO alarms, string tv_ids, long companyId) {
            return base.Channel.saveAlarm(alarms, tv_ids, companyId);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<string>> saveAlarmAsync(DigitalSignageUI.AlarmsServices.AlarmsInfoWTO alarms, string tv_ids, long companyId) {
            return base.Channel.saveAlarmAsync(alarms, tv_ids, companyId);
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.AlarmsServices.AlarmsInfoWTO[]> searchDataOnAlarms(DigitalSignageUI.AlarmsServices.AlarmsInfoWTO filter, DigitalSignageUI.AlarmsServices.PagingInfo paging) {
            return base.Channel.searchDataOnAlarms(filter, paging);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.AlarmsServices.AlarmsInfoWTO[]>> searchDataOnAlarmsAsync(DigitalSignageUI.AlarmsServices.AlarmsInfoWTO filter, DigitalSignageUI.AlarmsServices.PagingInfo paging) {
            return base.Channel.searchDataOnAlarmsAsync(filter, paging);
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.AlarmsServices.AlarmsInfoWTO[]> loadTvAlarms(long tvId, long companyId) {
            return base.Channel.loadTvAlarms(tvId, companyId);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.AlarmsServices.AlarmsInfoWTO[]>> loadTvAlarmsAsync(long tvId, long companyId) {
            return base.Channel.loadTvAlarmsAsync(tvId, companyId);
        }
    }
}
